version: 2
updates:
  - package-ecosystem: npm
    directory: /extension
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      dev-deps:
        dependency-type: development
        update-types:
          - patch
          - minor
      prod-deps:
        dependency-type: production
        update-types:
          - patch
          - minor
    labels:
      - dependencies
      - extension

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
